### Array
-------------------------------------------------
Ưu điểm của việc sử dụng Numpy so với Python thuần là việc Numpy có hỗ trợ mô phỏng được mảng nhiều chiều dễ dàng hơn.

Xem thêm về [mảng](https://github.com/Khoa-21501/learn-MachineLearning-akaicheese/blob/main/python-basic/list.ipynb) của Python thuần.

#### I. Import thư viện Numpy

In [1]:
import numpy as np

#### II. Khởi tạo một Array
##### 1. np.array()
###### a. Mảng 1 chiều

In [ ]:
# với mảng 1 chiều thì có thể gọi là một Vector
# với mỗi phần tử trong mảng là Scalar
array_vector = np.array([9, 8, 7, 6, 5])

In [ ]:
array_vector

array([9, 8, 7, 6, 5])

###### b. Mảng 2 chiều

In [ ]:
# với mảng 2 chiều thì có thể gọi là một Matrix
# với mỗi tập trong mảng là mỗi Vector
array_matrix = np.array([[3, 2, 1], [4, 5, 6]])

In [ ]:
array_matrix

array([[3, 2, 1],
       [4, 5, 6]])

In [ ]:
# số chiều của ma trận
# với ma trận này thì có 2 hàng và 3 cột
array_matrix.shape

(2, 3)

###### c. Mảng 3 chiều

In [ ]:
# với mảng 3 chiều thì có thể gọi là một Matrix 3 chiều
array_3D_matrix = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

In [ ]:
array_3D_matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# số chiều của ma trận 3 chiều
# với ma trận này thì mỗi phần có 2 hàng và chia làm 2 phần và mỗi phần có 3 cột
array_3D_matrix.shape

(2, 2, 3)

##### 2. np.zeros() | np.ones() | np.full()

- Tạo ra mảng có giá trị bằng nhau
  - np.zeros() tạo ra mảng có các giá trị bằng 0
    - Đầu vào là chiều của mảng dưới dạng tuple
  
  - np.ones() tạo ra mảng có các giá trị bằng 1
    - Đầu vào là chiều của mảng dưới dạng tuple
  
  - np.full() tạo ra mảng có các giá trị bằng nhau và bằng một số cho trước
    - Đầu vào là chiều của mảng dưới dạng tuple và giá trị cho trước 

###### a. Mảng 1 chiều
np.zeros()

In [ ]:
array_1D_zeros = np.zeros((6, ))

In [ ]:
array_1D_zeros

array([0., 0., 0., 0., 0., 0.])

np.ones()

In [ ]:
array_1D_ones = np.ones((7, ))

In [ ]:
array_1D_ones

array([1., 1., 1., 1., 1., 1., 1.])

np.full()

In [ ]:
array_1D_full_twentyone = np.full((5, ), 21)

In [ ]:
array_1D_full_twentyone

array([21, 21, 21, 21, 21])

###### b. Mảng 2 chiều
np.zeros()

In [ ]:
array_2D_zeros = np.zeros((5, 7))

In [ ]:
array_2D_zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

np.ones()

In [ ]:
array_2D_ones = np.ones((6, 3))

In [ ]:
array_2D_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

np.full()

In [ ]:
array_2D_full_five = np.full((4, 3), 5)

In [ ]:
array_2D_full_five

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

###### c. Mảng 3 chiều
np.zeros()

In [ ]:
array_3D_zeros = np.zeros((3, 4, 5))

In [ ]:
array_3D_zeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

np.ones()

In [ ]:
array_3D_ones = np.ones((5, 6, 2))

In [ ]:
array_3D_ones

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

np.full()

In [ ]:
array_3D_full_two = np.full((2, 5, 6), 2)

In [ ]:
array_3D_full_two

array([[[2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2]]])

##### 3. np.eye()
  - Tạo ra một ma trận đơn vị

In [ ]:
np.eye((6))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

##### 4. np.arange()
 - Tạo một mảng chạy từ 0 -> 8

In [ ]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

  - Tạo một mảng chạy từ 5 -> 15

In [ ]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

  - Tạo một mảng chạy từ 0 -> 12 và mỗi phần tử cách nhau 2 đơn vị

In [ ]:
np.arange(0, 12, 2)

array([ 0,  2,  4,  6,  8, 10])

##### 5. np.linspace()
  - Tạo ra một mảng chạy từ 1 -> 12 và gồm 6 phần tử trong mảng cách đều từ 1 -> 12

In [4]:
np.linspace(1, 12, 6)

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

##### 6. np.random.random()
  - Tạo một ma trận với các giá trị ngẫu nhiên

In [ ]:
np.random.random((5, 8))

array([[0.26732497, 0.79956576, 0.20870024, 0.63119461, 0.25588551,
        0.66399885, 0.04062925, 0.66392159],
       [0.45081932, 0.65307809, 0.4929539 , 0.85242613, 0.54109441,
        0.25950598, 0.31921717, 0.25181869],
       [0.23039461, 0.40296619, 0.01003726, 0.08947942, 0.74743044,
        0.44233326, 0.77679527, 0.45490816],
       [0.05834876, 0.48970114, 0.21985538, 0.04384252, 0.61534148,
        0.23699899, 0.21474943, 0.35269348],
       [0.43415143, 0.14750362, 0.36606413, 0.67082837, 0.68829589,
        0.4475433 , 0.14270888, 0.37337436]])

##### 7. np.random.randint()
  - Tạo một mảng với các giá trị số nguyên, các giá trị từ 0 -> 12 và gồm 6 phần tử

In [28]:
np.random.randint(0, 12, 6)

array([10,  3,  2,  2,  2, 11])

##### 8. np.random.shuffle()
  - Xáo trộn của một mảng có sẵn

In [38]:
a = np.arange(10)

In [39]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.random.shuffle(a)

In [41]:
a

array([2, 4, 7, 1, 6, 8, 9, 3, 5, 0])

##### 9. np.random.choice()
  - Chọn ngẫu nhiên một phần tử trong mảng

In [42]:
a = np.array([1, 3, 5, 7, 9, 11])

In [43]:
a

array([ 1,  3,  5,  7,  9, 11])

In [44]:
np.random.choice(a)

5

##### 10. np.random.random_integers()
  - Tạo một mảng từ 4 -> 10 với 3 phần tử

In [46]:
np.random.random_integers(4, 10, 3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(4, 10 + 1) instead
  """Entry point for launching an IPython kernel.


array([4, 7, 6])

##### 11. np.shape() | np.reshape() | np.size() | np.dtype()
  - Thay đổi số chiều của mảng

In [5]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
# số chiều của mảng
np.shape(a)

(8,)

In [16]:
# tổng số phần tử của mảng
np.size(a)

8

In [19]:
# kiểu dữ liệu của mảng
a.dtype

dtype('int64')

In [9]:
# thay đổi số chiều của mảng
# với 2 hàng và 4 cột
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# thay đổi số chiều của mảng
# với 2 phần và mỗi phần gồm 2 hàng và 2 cột
a.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

##### 12. So sánh và tính toán trong mảng

In [20]:
array_2D_np = np.array([[4, 5, 6], [9, 8, 7]])

In [23]:
# các phần tử trong mảng lớn 5
array_2D_np > 5

array([[False, False,  True],
       [ True,  True,  True]])

In [24]:
# tổng một con số với mảng
array_2D_np + 2

array([[ 6,  7,  8],
       [11, 10,  9]])

In [25]:
# hiệu một con số với mảng
array_2D_np - 3

array([[1, 2, 3],
       [6, 5, 4]])

In [26]:
# tích một con số với mảng
array_2D_np * 4

array([[16, 20, 24],
       [36, 32, 28]])

In [27]:
# thương một con số với mảng
array_2D_np / 2

array([[2. , 2.5, 3. ],
       [4.5, 4. , 3.5]])

##### 13. Tìm giá trị min, max, mean, var, std của mảng

In [29]:
b = np.array([[3, 5, 7], [4, 6, 8]])

In [30]:
# tìm giá trị nhỏ nhất của mảng
b.min()

3

In [31]:
# tìm giá trị lớn nhất của mảng
b.max()

8

In [33]:
# tìm giá trị trung bình của mảng
b.mean()

5.5

In [34]:
# tìm giá trị phương sai của mảng
b.var()

2.9166666666666665

In [35]:
# tìm giá trị độ lệch chuẩn của mảng
b.std()

1.707825127659933

Vào đây để tìm hiểu thêm [Numpy (Array)](https://numpy.org/doc/stable/reference/generated/numpy.array.html)