### Array
-------------------------------------------------
Ưu điểm của việc sử dụng Numpy so với Python thuần là việc Numpy có hỗ trợ mô phỏng được mảng nhiều chiều dễ dàng hơn.

Xem thêm về [mảng](https://github.com/Khoa-21501/learn-MachineLearning-akaicheese/blob/main/python-basic/list.ipynb) của Python thuần.

#### I. Import thư viện Numpy

In [2]:
import numpy as np

#### II. Khởi tạo một Array
##### 1. np.array()
###### a. Mảng 1 chiều

In [ ]:
# với mảng 1 chiều thì có thể gọi là một Vector
# với mỗi phần tử trong mảng là Scalar
array_vector = np.array([9, 8, 7, 6, 5])

In [ ]:
array_vector

array([9, 8, 7, 6, 5])

###### b. Mảng 2 chiều

In [ ]:
# với mảng 2 chiều thì có thể gọi là một Matrix
# với mỗi tập trong mảng là mỗi Vector
array_matrix = np.array([[3, 2, 1], [4, 5, 6]])

In [ ]:
array_matrix

array([[3, 2, 1],
       [4, 5, 6]])

In [ ]:
# số chiều của ma trận
# với ma trận này thì có 2 hàng và 3 cột
array_matrix.shape

(2, 3)

###### c. Mảng 3 chiều

In [ ]:
# với mảng 3 chiều thì có thể gọi là một Matrix 3 chiều
array_3D_matrix = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

In [ ]:
array_3D_matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# số chiều của ma trận 3 chiều
# với ma trận này thì mỗi phần có 2 hàng và chia làm 2 phần và mỗi phần có 3 cột
array_3D_matrix.shape

(2, 2, 3)

##### 2. np.zeros() | np.ones() | np.full()

- Tạo ra mảng có giá trị bằng nhau
  - np.zeros() tạo ra mảng có các giá trị bằng 0
    - Đầu vào là chiều của mảng dưới dạng tuple
  
  - np.ones() tạo ra mảng có các giá trị bằng 1
    - Đầu vào là chiều của mảng dưới dạng tuple
  
  - np.full() tạo ra mảng có các giá trị bằng nhau và bằng một số cho trước
    - Đầu vào là chiều của mảng dưới dạng tuple và giá trị cho trước 

###### a. Mảng 1 chiều
np.zeros()

In [ ]:
array_1D_zeros = np.zeros((6, ))

In [ ]:
array_1D_zeros

array([0., 0., 0., 0., 0., 0.])

np.ones()

In [ ]:
array_1D_ones = np.ones((7, ))

In [ ]:
array_1D_ones

array([1., 1., 1., 1., 1., 1., 1.])

np.full()

In [ ]:
array_1D_full_twentyone = np.full((5, ), 21)

In [ ]:
array_1D_full_twentyone

array([21, 21, 21, 21, 21])

###### b. Mảng 2 chiều
np.zeros()

In [ ]:
array_2D_zeros = np.zeros((5, 7))

In [ ]:
array_2D_zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

np.ones()

In [ ]:
array_2D_ones = np.ones((6, 3))

In [ ]:
array_2D_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

np.full()

In [ ]:
array_2D_full_five = np.full((4, 3), 5)

In [ ]:
array_2D_full_five

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

###### c. Mảng 3 chiều
np.zeros()

In [ ]:
array_3D_zeros = np.zeros((3, 4, 5))

In [ ]:
array_3D_zeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

np.ones()

In [ ]:
array_3D_ones = np.ones((5, 6, 2))

In [ ]:
array_3D_ones

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

np.full()

In [ ]:
array_3D_full_two = np.full((2, 5, 6), 2)

In [ ]:
array_3D_full_two

array([[[2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2]]])

##### 3. np.eye()
  - Tạo ra một ma trận đơn vị

In [4]:
np.eye((6))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

##### 4. np.arange()
 - Tạo một mảng chạy từ 0 -> 8

In [5]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

  - Tạo một mảng chạy từ 5 -> 15

In [6]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

  - Tạo một mảng chạy từ 0 -> 12 và mỗi phần tử cách nhau 2 đơn vị

In [7]:
np.arange(0, 12, 2)

array([ 0,  2,  4,  6,  8, 10])

##### 5. np.random.random()
  - Tạo một ma trận với các giá trị ngẫu nhiên

In [9]:
np.random.random((5, 8))

array([[0.26732497, 0.79956576, 0.20870024, 0.63119461, 0.25588551,
        0.66399885, 0.04062925, 0.66392159],
       [0.45081932, 0.65307809, 0.4929539 , 0.85242613, 0.54109441,
        0.25950598, 0.31921717, 0.25181869],
       [0.23039461, 0.40296619, 0.01003726, 0.08947942, 0.74743044,
        0.44233326, 0.77679527, 0.45490816],
       [0.05834876, 0.48970114, 0.21985538, 0.04384252, 0.61534148,
        0.23699899, 0.21474943, 0.35269348],
       [0.43415143, 0.14750362, 0.36606413, 0.67082837, 0.68829589,
        0.4475433 , 0.14270888, 0.37337436]])

Vào đây để tìm hiểu thêm [Numpy (Array)](https://numpy.org/doc/stable/reference/generated/numpy.array.html)