### Numpy
-----------------------------------------------------------------------------

Tìm hiểu thêm tại [Numpy](https://www.w3schools.com/python/numpy/default.asp)

#### Import thư viện Numpy

In [1]:
import numpy as np

#### Tạo Numpy Array từ Python List

In [2]:
np.array([2, 4, 6 ,8])

array([2, 4, 6, 8])

In [3]:
[2.15, 2, 1, 5]

[2.15, 2, 1, 5]

In [4]:
np.array([2.15, 2, 1, 5])

array([2.15, 2.  , 1.  , 5.  ])

In [5]:
np.array([3, 5, 7, 9, 11], dtype="float32")

array([ 3.,  5.,  7.,  9., 11.], dtype=float32)

In [6]:
np.array([2.0, 1.0, 3, 5], dtype="int64")

array([2, 1, 3, 5])

In [7]:
array1 = np.array([1, 2, 3, 4, 5])

In [8]:
type(array1)

numpy.ndarray

In [11]:
array1.shape

(5,)

In [13]:
array1.ndim

1

In [15]:
array1.dtype

dtype('int64')

In [20]:
array1.size

5

In [16]:
array2 = np.array([
       [1.5, 2.2, 3.1, 4.4],
       [5.5, 6.6, 7.7, 8.8]            
])

In [17]:
type(array2)

numpy.ndarray

In [18]:
array2.shape

(2, 4)

In [19]:
array2.ndim

2

In [21]:
array2.dtype

dtype('float64')

In [22]:
array2.size

8

#### Tạo Numpy Array từ hàm có sẵn

**zeros, ones, full, arange, linspace**

In [23]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.zeros([1,2], dtype="int64")

array([[0, 0]])

In [27]:
np.ones([4, 5], dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
np.ones([2, 5], dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# tạo mảng Numpy từ 0 đến 22 và cách nhau 2 đơn vị
np.arange(0, 22, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
np.full((3, 4), 6.9)

array([[6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9]])

In [30]:
# tạo mảng Numpy được chia đều từ 0 đến 1 bao gồm số giá trị cần chia ra được cho trước
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**random**

In [37]:
# Random mà không thay đổi gì (seed)
np.random.seed(0)

np.random.random((3, 3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [38]:
np.random.normal(0, 1, (4, 4))

array([[ 1.26611853, -0.50587654,  2.54520078,  1.08081191],
       [ 0.48431215,  0.57914048, -0.18158257,  1.41020463],
       [-0.37447169,  0.27519832, -0.96075461,  0.37692697],
       [ 0.03343893,  0.68056724, -1.56349669, -0.56669762]])

In [39]:
np.random.randint(0, 10, (3, 5))

array([[2, 7, 2, 0, 0],
       [4, 5, 5, 6, 8],
       [4, 1, 4, 9, 8]])

In [40]:
np.random.rand(4, 4)

array([[0.90234858, 0.09928035, 0.96980907, 0.65314004],
       [0.17090959, 0.35815217, 0.75068614, 0.60783067],
       [0.32504723, 0.03842543, 0.63427406, 0.95894927],
       [0.65279032, 0.63505887, 0.99529957, 0.58185033]])

#### Chỉ mục và cắt mảng

**Mảng 1 chiều**

In [41]:
a1 = np.random.randint(20, size = 5)

In [42]:
a1

array([14, 15,  3, 15, 13])

In [43]:
a1[1]

15

In [44]:
a1[3]

15

In [45]:
a1[-3]

3

In [47]:
a1[0], a1[2], a1[4]

(14, 3, 13)

**Mảng nhiều chiều**

In [48]:
a2 = np.random.randint(10, size = (3, 5))

In [49]:
a2

array([[5, 5, 0, 1, 5],
       [9, 3, 0, 5, 0],
       [1, 2, 4, 2, 0]])

In [51]:
a2[0,2]

0

In [52]:
a2[2,3]

2

In [53]:
a2[-2,-2]

5

In [54]:
a2[0, 2] = 5

In [55]:
a2[0, 3] = 5

In [56]:
a2

array([[5, 5, 5, 5, 5],
       [9, 3, 0, 5, 0],
       [1, 2, 4, 2, 0]])

**Cắt Mảng**

**x[start:stop:step]**

In [60]:
x1 = np.array([1, 2, 3, 4, 5, 6])

In [61]:
x1

array([1, 2, 3, 4, 5, 6])

In [62]:
x1[0:4]

array([1, 2, 3, 4])

In [63]:
x1[1:3]

array([2, 3])

In [65]:
# lấy tất cả các phần tử cách nhau 2 
x1[::2]

array([1, 3, 5])

In [66]:
x2 = np.array([
    [1, 2, 3],
    [6, 5, 4]           
])

In [67]:
# lấy ra 2 hàng và 2 cột đầu
x2[:2,:2]

array([[1, 2],
       [6, 5]])

In [68]:
# lấy ra 2 hàng và 2 cột cuối
x2[:2,1:3]

array([[2, 3],
       [5, 4]])

In [69]:
# lấy ra 1 hàng và tất cả các cột
x2[:1,:]

array([[1, 2, 3]])

#### Thay đổi chiều và chuyển vị mảng

In [75]:
arr = np.arange(1, 10)

In [76]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr.shape

(9,)

In [78]:
arr.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
x = np.array([1, 2, 3, 4])

In [80]:
x.shape

(4,)

In [83]:
x.reshape((2,2)).shape

(2, 2)

In [84]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])

In [87]:
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
transposed_v1 = arr_2D.T

In [86]:
transposed_v1

array([[1, 4],
       [2, 5],
       [3, 6]])

In [88]:
transposed_v2 = np.transpose(arr_2D)

In [89]:
transposed_v2

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Nối và tách các mảng

**Nối mảng**

In [90]:
x = np.array([1, 2, 3, 4])
y = np.array([4, 5, 6, 7])

In [95]:
np.concatenate((x, y))

array([1, 2, 3, 4, 4, 5, 6, 7])

In [96]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [97]:
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

In [100]:
np.concatenate((arr1, arr2), axis=0) # nối theo hàng (mặc định)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [99]:
np.concatenate((arr1, arr2), axis=1) # nối theo cột

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [109]:
a = np.array([1, 2, 3])
a1 = np.array([[1],
               [2]])

b = np.array([[4, 5, 6],
              [7, 8, 9]])

In [104]:
# vstack (vertical - theo hàng nối mảng 1 chiều với mảng 2 chiều ) 
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
# hstack (horizontal - theo cột nối mảng 1 chiều với mảng 2 chiều ) 
np.hstack((a1, b))

array([[1, 4, 5, 6],
       [2, 7, 8, 9]])

**Cắt Mảng**

In [111]:
x = np.array([1, 2, 3, 7, 8, 4, 5, 6])

In [113]:
x1, x2, x3 = np.split(x, [3, 5])

In [114]:
x1

array([1, 2, 3])

In [115]:
x3

array([4, 5, 6])

In [116]:
x2

array([7, 8])

In [136]:
arr = np.arange(16).reshape(4,4)

In [137]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [140]:
arr_vsplit = np.vsplit(arr, 2)

In [141]:
arr_vsplit

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [142]:
x = np.arange(16.0).reshape(4, 4)

In [143]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [144]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

#### Tính toán với mảng

In [145]:
a = np.arange(4)

In [146]:
a

array([0, 1, 2, 3])

In [147]:
a + 5 # mảng với số

array([5, 6, 7, 8])

In [150]:
b = np.ones((4,4))

In [151]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [152]:
b * 2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [153]:
a + b # cùng số chiều của cột của mảng trước và hàng của mảng sau

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [157]:
a * b

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [155]:
c = np.arange(4).reshape((4,1))

In [156]:
c

array([[0],
       [1],
       [2],
       [3]])

In [159]:
a - c

array([[ 0,  1,  2,  3],
       [-1,  0,  1,  2],
       [-2, -1,  0,  1],
       [-3, -2, -1,  0]])

#### Thao tác và so sánh các mảng

In [160]:
list_number = [1, 2, 3, 4]

In [161]:
arr = np.array(list_number)

In [162]:
arr

array([1, 2, 3, 4])

In [163]:
# Python sum()
sum(arr)

10

In [164]:
# Numpy sum()
np.sum(arr)

10

In [166]:
# Tạo một mảng Numpy cực lớn
massive_array = np.random.random(10000)

In [167]:
massive_array[:5]

array([0.05695837, 0.27267993, 0.07212403, 0.54761111, 0.3518183 ])

In [169]:
massive_array.size

10000

In [170]:
massive_array.shape

(10000,)

In [171]:
%timeit sum(massive_array) # Python sum() built-in function
%timeit np.sum(massive_array) # Numpy sum()

1000 loops, best of 5: 841 µs per loop
The slowest run took 104.92 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 7.64 µs per loop


In [172]:
np.mean(massive_array)

0.49489483544108326

In [173]:
np.max(massive_array)

0.9999620173413053

In [174]:
np.min(massive_array)

0.00016644134026855273

In [175]:
price_bottles = [15000, 86000, 8000, 46000, 110000]

In [176]:
price_bottles = np.array(price_bottles)

In [177]:
price_bottles

array([ 15000,  86000,   8000,  46000, 110000])

In [186]:
np.mean(price_bottles)

53000.0

In [179]:
# độ lệch chuẩn
np.std(price_bottles)

39638.36525387999

In [182]:
# tính phương sai 
var_price_bottles = np.var(price_bottles)

In [183]:
var_price_bottles

1571200000.0

In [185]:
# tính độ lệch chuẩn từ phương sai
np.sqrt(var_price_bottles)

39638.36525387999

#### Sắp xếp mảng

In [187]:
x = np.array([15, 10, 40, 25, 30, 55, 5])

In [188]:
np.sort(x)

array([ 5, 10, 15, 25, 30, 40, 55])

In [190]:
np.argsort(x) # return index of sorted array

array([6, 1, 0, 3, 4, 2, 5])

In [192]:
np.random.seed(23)

MatA = np.random.randint(0, 10, size=(3, 5))

In [193]:
MatA

array([[3, 6, 8, 9, 6],
       [8, 7, 9, 3, 6],
       [1, 2, 5, 5, 0]])

In [195]:
np.sort(MatA, axis=0) # sắp xếp theo cột

array([[1, 2, 5, 3, 0],
       [3, 6, 8, 5, 6],
       [8, 7, 9, 9, 6]])

In [196]:
np.sort(MatA, axis=1) # sắp xếp theo hàng

array([[3, 6, 6, 8, 9],
       [3, 6, 7, 8, 9],
       [0, 1, 2, 5, 5]])

#### Đại số tuyến tính với Numpy

In [197]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [198]:
B = np.array([[2, 4, 6, 8],
              [1, 3, 5, 7],
              [7, 3, 6, 4]])

In [200]:
# Ma trận A (3x3) nhân được với ma trận B (3x4)
A.dot(B)

array([[ 25,  19,  34,  34],
       [ 55,  49,  85,  91],
       [ 85,  79, 136, 148]])

In [206]:
# tổng của hàng trước nhân cột sau của từng phần tử tương ứng
1*2 + 2*1 + 3*7

25

In [201]:
# Ma trận B (3x4) không nhân được với ma trận A (3x3)
B.dot(A)

ValueError: ignored

In [208]:
# tương tự như trên
A @ B

array([[ 25,  19,  34,  34],
       [ 55,  49,  85,  91],
       [ 85,  79, 136, 148]])